### ISSUE TITLE
`pyproject.toml` allows incompatible version of openMCMC

### ISSUE THREAD

**Issue by rudymcintyre** [sede-open/pyELQ#12]
Under latest version of main and openMCMC v1.0.4, all tests under the file `tests/test_model.py` fail because they attempt to pass `n_thin` to the constructor of MCMC. Updating to openMCMC v1.0.5 resolves this and all tests pass. The version specification in `pyproject.toml` should be altered to reflect this.

**Comment by bvandekerkhof** [comment]
Good spot, will change, thanks.
